### ISSUE TITLE
Can't build with gcc 6

### ISSUE THREAD

**Issue by darkbasic** [OpenMW/osg#4]
Scanning dependencies of target osgdb_xine
[ 53%] Building CXX object src/osgPlugins/lwo/CMakeFiles/osgdb_lwo.dir/old_Lwo2.o
[ 53%] Building C object src/osgPlugins/xine/CMakeFiles/osgdb_xine.dir/video_out_rgb.o
/home/niko/devel/openscenegraph-git/src/osg/src/osgPlugins/xine/video_out_rgb.c: In function ‘rgbout_update_frame_format’:
/home/niko/devel/openscenegraph-git/src/osg/src/osgPlugins/xine/video_out_rgb.c:2325:41: warning: implicit declaration of function ‘xine_xmalloc_aligned’ [-Wimplicit-function-declaration]
    frame->vo_frame.base[0] = (uint8_t_) xine_xmalloc_aligned(16,
                                         ^~~~~~~~~~~~~~~~~~~~
/home/niko/devel/openscenegraph-git/src/osg/src/osgPlugins/xine/video_out_rgb.c:2325:30: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
    frame->vo_frame.base[0] = (uint8_t_) xine_xmalloc_aligned(16,
                              ^
/home/niko/devel/openscenegraph-git/src/osg/src/osgPlugins/xine/video_out_rgb.c:2328:30: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
    frame->vo_frame.base[1] = (uint8_t_) xine_xmalloc_aligned(16,
                              ^
/home/niko/devel/openscenegraph-git/src/osg/src/osgPlugins/xine/video_out_rgb.c:2331:30: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
    frame->vo_frame.base[2] = (uint8_t_) xine_xmalloc_aligned(16,
                              ^
/home/niko/devel/openscenegraph-git/src/osg/src/osgPlugins/xine/video_out_rgb.c:2349:30: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
    frame->vo_frame.base[0] = (uint8_t_) xine_xmalloc_aligned(16,
                              ^
[ 53%] Building CXX object src/osgPlugins/gles/CMakeFiles/osgdb_gles.dir/TriangleStripVisitor.o
[ 53%] Building CXX object src/osgPlugins/xine/CMakeFiles/osgdb_xine.dir/ReaderWriterXine.o
[ 53%] Building CXX object src/osgPlugins/gles/CMakeFiles/osgdb_gles.dir/IndexMeshVisitor.o
[ 53%] Building CXX object src/osgPlugins/ply/CMakeFiles/osgdb_ply.dir/vertexData.o
[ 53%] Linking CXX shared module ../../../lib/osgPlugins-3.4.0/osgdb_xine.so
[ 53%] Built target osgdb_xine
Scanning dependencies of target osgdb_ffmpeg
[ 53%] Building CXX object src/osgPlugins/ffmpeg/CMakeFiles/osgdb_ffmpeg.dir/FFmpegClocks.o
[ 53%] Building CXX object src/osgPlugins/lwo/CMakeFiles/osgdb_lwo.dir/old_Lwo2Layer.o
[ 53%] Building CXX object src/osgPlugins/ffmpeg/CMakeFiles/osgdb_ffmpeg.dir/FFmpegDecoderAudio.o
/home/niko/devel/openscenegraph-git/src/osg/src/osgPlugins/ffmpeg/FFmpegDecoderAudio.cpp: In member function ‘void osgFFmpeg::FFmpegDecoderAudio::open(AVStream_, osgFFmpeg::FFmpegParameters_)’:
/home/niko/devel/openscenegraph-git/src/osg/src/osgPlugins/ffmpeg/FFmpegDecoderAudio.cpp:230:20: error: ‘AVCodecContext {aka struct AVCodecContext}’ has no member named ‘get_buffer’; did you mean ‘get_buffer2’?
         m_context->get_buffer = avcodec_default_get_buffer;
                    ^~~~~~~~~~
/home/niko/devel/openscenegraph-git/src/osg/src/osgPlugins/ffmpeg/FFmpegDecoderAudio.cpp:230:33: error: ‘avcodec_default_get_buffer’ was not declared in this scope
         m_context->get_buffer = avcodec_default_get_buffer;
                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/niko/devel/openscenegraph-git/src/osg/src/osgPlugins/ffmpeg/FFmpegDecoderAudio.cpp:231:20: error: ‘AVCodecContext {aka struct AVCodecContext}’ has no member named ‘release_buffer’; did you mean ‘get_buffer2’?
         m_context->release_buffer = avcodec_default_release_buffer;
                    ^~~~~~~~~~~~~~
/home/niko/devel/openscenegraph-git/src/osg/src/osgPlugins/ffmpeg/FFmpegDecoderAudio.cpp:231:37: error: ‘avcodec_default_release_buffer’ was not declared in this scope
         m_context->release_buffer = avcodec_default_release_buffer;
                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/osgPlugins/ffmpeg/CMakeFiles/osgdb_ffmpeg.dir/build.make:86: set di istruzioni per l'obiettivo "src/osgPlugins/ffmpeg/CMakeFiles/osgdb_ffmpeg.dir/FFmpegDecoderAudio.o" non riuscito
make[2]: *_\* [src/osgPlugins/ffmpeg/CMakeFiles/osgdb_ffmpeg.dir/FFmpegDecoderAudio.o] Errore 1
CMakeFiles/Makefile2:6512: set di istruzioni per l'obiettivo "src/osgPlugins/ffmpeg/CMakeFiles/osgdb_ffmpeg.dir/all" non riuscito
make[1]: **\* [src/osgPlugins/ffmpeg/CMakeFiles/osgdb_ffmpeg.dir/all] Errore 2
make[1]: **\* Attesa per i processi non terminati....
[ 53%] Building CXX object src/osgPlugins/lwo/CMakeFiles/osgdb_lwo.dir/Polygon.o
[ 53%] Building CXX object src/osgPlugins/ply/CMakeFiles/osgdb_ply.dir/plyfile.o
[ 53%] Building CXX object src/osgPlugins/lwo/CMakeFiles/osgdb_lwo.dir/ReaderWriterLWO.o
[ 53%] Building CXX object src/osgPlugins/lwo/CMakeFiles/osgdb_lwo.dir/Surface.o
/home/niko/devel/openscenegraph-git/src/osg/src/osgPlugins/lwo/ReaderWriterLWO.cpp: In member function ‘virtual osgDB::ReaderWriter::ReadResult ReaderWriterLWO::readNode_old_LWO2(const string&, const Options_) const’:
/home/niko/devel/openscenegraph-git/src/osg/src/osgPlugins/lwo/ReaderWriterLWO.cpp:148:10: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
     std::auto_ptr<Lwo2> lwo2(new Lwo2());
          ^~~~~~~~
In file included from /usr/include/c++/6.1.1/memory:81:0,
                 from /home/niko/devel/openscenegraph-git/src/osg/src/osgPlugins/lwo/ReaderWriterLWO.cpp:19:
/usr/include/c++/6.1.1/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
[ 53%] Linking CXX shared module ../../../lib/osgPlugins-3.4.0/osgdb_ply.so
[ 53%] Built target osgdb_ply
[ 53%] Building CXX object src/osgPlugins/lwo/CMakeFiles/osgdb_lwo.dir/Tessellator.o
[ 53%] Building CXX object src/osgPlugins/gles/CMakeFiles/osgdb_gles.dir/UnIndexMeshVisitor.o
[ 53%] Building CXX object src/osgPlugins/lwo/CMakeFiles/osgdb_lwo.dir/Unit.o
[ 53%] Building CXX object src/osgPlugins/lwo/CMakeFiles/osgdb_lwo.dir/VertexMap.o
[ 54%] Building CXX object src/osgPlugins/gles/CMakeFiles/osgdb_gles.dir/forsythtriangleorderoptimizer.o
[ 54%] Linking CXX shared module ../../../lib/osgPlugins-3.4.0/osgdb_lwo.so
[ 54%] Built target osgdb_lwo
[ 54%] Linking CXX shared module ../../../lib/osgPlugins-3.4.0/osgdb_gles.so
[ 54%] Built target osgdb_gles
Makefile:127: set di istruzioni per l'obiettivo "all" non riuscito
make: *_\* [all] Errore 2
==> ERRORE: Si è verificato un errore in build().
    L'operazione sta per essere interrotta...

**Comment by ghost** [comment]
You can disable osgPlugins/ffmpeg, we don't need it for OpenMW.

**Comment by ghost** [comment]
c0adcc0b43f37931ccb70e3e2b4227c4a86cfaaf
